server:
  servlet:
    context-path: ${CONTEXT_PATH:/cash}
  port: ${SERVER_PORT:8801}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?verifyServerCertificate=false&useSSL=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

wx:
  appid: ${WX_APPID}
  appsecret: ${WX_APPSECRET}

cos:
  secretId: ${COS_SECRET_ID}
  secretKey: ${COS_SECRET_KEY}
  region: ${COS_REGION}
  bucketName: ${COS_BUCKET_NAME}